package projecteuler;

/**
 * 
 * @author Andrzej Ruszczewski
 * 
 */
public class Problem2 {

	static int numOfCalls;

	/**
	 * Each new term in the Fibonacci sequence is generated by adding the
	 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 * 
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * 
	 * By considering the terms in the Fibonacci sequence whose values do not
	 * exceed four million, find the sum of the even-valued terms.
	 */
	public static void main(String[] args) {

		int upTo = 4000000;
		int sum = 0;
		int a = 1, b = 2, tmp;
		
		while (a < upTo) {
			if (a % 2 == 0)
				sum += a;
			tmp = b;
			b = a + b;
			a = tmp;
		}

		System.out.println(sum);
		
	}

}
